Repository CloudNationHQ/terraform-azure-sa, pull requests merged in 2025-03, with the labels that each got.

#150 fix: Add list permission to permission scope
  main.tf
Labels: enhancement

#153 feat: format documentation to include type definitions and removed redundant random provider
  GOALS.md
  Makefile
  README.md
  examples/containers-blob/README.md
  examples/default/README.md
  examples/file-systems/README.md
  examples/local-users/README.md
  examples/management-policies/README.md
  examples/management-policies/main.tf
  examples/management-policies/mgt-policies.tf
  examples/network-rules/README.md
  examples/private-endpoint/README.md
  examples/queues/README.md
  examples/shares/README.md
  main.tf
  terraform.tf
  variables.tf
Labels: documentation, enhancement

#155 fix: resolve for each sensitivity issue in containers, queues and local users
  main.tf
Labels: bug

#158 fix: change default value identity_ids in user assigned identity
  main.tf
  variables.tf
Labels: bug

#161 feat: improve contributor visibility
  README.md
Labels: documentation
